from flask import request, Flask
import json
from flask_caching import Cache
import time

app = Flask(__name__)
app.config.from_object('config.Config')
cache = Cache(app)

def timeConsumingFunc():
	time.sleep(5)
	return

@app.route('/')
@cache.cached(timeout=30, query_string=True)
def hello_world():
	timeConsumingFunc()
	return 'Hello there.! \n Content Generated by' + __file__
if __name__ == '__main__':
	app.run(debug=True, host='0.0.0.0')
